<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9670b5d8-e81e-4d66-9875-853394e36d4d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\VoiceController.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.28">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Twilio" Version="7.14.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="wwwroot\admin\" />
    <Folder Include="wwwroot\recordings\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KolHaNitzachon.PhoneSystem.Application\KolHaNitzachon.PhoneSystem.Application.csproj" />
    <ProjectReference Include="..\KolHaNitzachon.PhoneSystem.Domain\KolHaNitzachon.PhoneSystem.Domain.csproj" />
    <ProjectReference Include="..\KolHaNitzachon.PhoneSystem.Infrastructure\KolHaNitzachon.PhoneSystem.Infrastructure.csproj" />
    <ProjectReference Include="..\KolHaNitzachon.PhoneSystem.Shared\KolHaNitzachon.PhoneSystem.Shared.csproj" />
  </ItemGroup>

</Project>
